name: CI

on:
  push:
    branches: [master, tests]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Build Python ${{ matrix.python_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        node_version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 13

      - name: Setup PSQL
        run: psql -U postgres -f schema.sql
      - name: Setup Config
        run: cp config.py.example config.py
      - name: Lint Code
        run: pylint main.py gc.py stats.py
      - name: Run Main
        run: python3 main.py &
